spring:
  application:
    name: focusr-be
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/focusr}
    username: ${DATABASE_USERNAME:focusr}
    password: ${DATABASE_PASSWORD:focusr}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
